debug: false
management.endpoints.web.exposure.include: "*"

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: hungry1234
    key-alias: tomcat
    http2:
      enabled: true
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hungry?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: root
  jpa:
    open-in-view: false
    ## defer-datasource-initialization: false sql.init ??? ???
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      connection.characterEncoding: utf8mb4
      connection.useUnicode: true
#      hibernate:
#        ejb:
#          use_class_enhancer=true:


